#!/bin/bash
set -e

POSTGRESQL_USER=${POSTGRESQL_USER:-"docker"}
POSTGRESQL_PASS=${POSTGRESQL_PASS:-"docker"}
POSTGRESQL_DB=${POSTGRESQL_DB:-"docker"}

POSTGRESQL_BIN=/usr/pgsql-9.3/bin/postgres
POSTGRESQL_DATA="/var/lib/pgsql/9.3/main"
POSTGRESQL_CONFIG_FILE=/var/lib/pgsql/9.3/main/postgresql.conf

if [ ! -d $POSTGRESQL_DATA ]; then
    mkdir -p $POSTGRESQL_DATA
    chown -R postgres:postgres $POSTGRESQL_DATA
    sudo -u postgres /usr/pgsql-9.3/bin/initdb -D $POSTGRESQL_DATA
   # ln -s /etc/ssl/certs/ssl-cert-snakeoil.pem $POSTGRESQL_DATA/server.crt
   # ln -s /etc/ssl/private/ssl-cert-snakeoil.key $POSTGRESQL_DATA/server.key

    sed -i -e "s/^#listen_addresses\s*=\s*'localhost'/listen_addresses = '*'/g" $POSTGRESQL_DATA/postgresql.conf
    sed -i -e "s/^#port\s*=\s*5432/port = 5432/g" $POSTGRESQL_DATA/postgresql.conf
    echo "host    all             all             0.0.0.0/0       md5">>$POSTGRESQL_DATA/pg_hba.conf

    sudo -u postgres $POSTGRESQL_BIN --single -D $POSTGRESQL_DATA <<< "CREATE USER $POSTGRESQL_USER WITH SUPERUSER;"
    sudo -u postgres $POSTGRESQL_BIN --single -D $POSTGRESQL_DATA <<< "ALTER USER $POSTGRESQL_USER WITH PASSWORD '$POSTGRESQL_PASS';"
    sudo -u postgres $POSTGRESQL_BIN --single -D $POSTGRESQL_DATA <<< "CREATE DATABASE $POSTGRESQL_DB OWNER $POSTGRESQL_USER;"
fi
exec sudo -u postgres $POSTGRESQL_BIN -D $POSTGRESQL_DATA 
